In [1]:
import pandas as pd

from bokeh.io import curdoc
from bokeh.layouts import row, column
from bokeh.models import ColumnDataSource, DatetimeTickFormatter, HoverTool
from bokeh.models.widgets import PreText, Select
from bokeh.plotting import figure, show

In [2]:
from datetime import datetime
import numpy as np

In [3]:
try:
    from functools import lru_cache
except ImportError:
    print("WARNING: Cache for this example is available on Python 3 only.")
    def lru_cache():
        def dec(f):
            def _(*args, **kws):
                return f(*args, **kws)
            return
        return dec

In [4]:
df = pd.read_csv("AMST3_SepOct.csv")
df = df[['Time stop', 'Organic', 'Sulfate', 'Ammonium', 'Nitrate', 'Chloride']]
datentime = [datetime.strptime(entry,'%m/%d/%y %H:%M') for entry in df['Time stop']]
df['datentime'] = datentime
#df = df.set_index('datentime')
df

,Time stop,Organic,Sulfate,Ammonium,Nitrate,Chloride,datentime
0,9/13/14 17:47,11.94720,1.758410,0.550953,0.290176,0.015616,2014-09-13 17:47:00
1,9/13/14 17:55,11.20270,1.590140,0.515114,0.211021,0.013689,2014-09-13 17:55:00
2,9/13/14 18:03,10.73810,1.484200,0.456858,0.174378,0.014700,2014-09-13 18:03:00
3,9/13/14 18:11,11.26250,1.562690,0.477693,0.174844,0.017399,2014-09-13 18:11:00
4,9/13/14 18:19,11.69100,1.582690,0.503957,0.194480,0.016549,2014-09-13 18:19:00
5,9/13/14 18:27,11.38780,1.580270,0.510905,0.164823,0.018170,2014-09-13 18:27:00
6,9/13/14 18:35,10.95210,1.450210,0.453779,0.162619,0.008872,2014-09-13 18:35:00
7,9/13/14 18:43,10.92600,1.433650,0.476453,0.152684,0.016209,2014-09-13 18:43:00
8,9/13/14 18:51,3.88525,0.595637,0.171677,0.038497,0.009524,2014-09-13 18:51:00
9,9/13/14 18:59,3.55995,0.596208,0.174129,0.047259,0.009437,2014-09-13 18:59:00
10,9/13/14 19:07,5.94130,0.900445,0.284233,0.046628,0.010277,2014-09-13 19:07:00
11,9/13/14 19:15,5.81877,0.900757,0.275290,0.082913,0.009717,2014-09-13 19:15:00
12,9/13/14 19:23,4.63620,0.753188,0.230268,0.043465,0.008388,2014-09-13 19:23:00
13,9/13/14 19:31,4.92573,0.777560,0.259077,0.071588,0.011794,2014-09-13 19:31:00
14,9/13/14 19:39,4.74542,0.735238,0.239229,0.055658,0.008778,2014-09-13 19:39:00
15,9/13/14 19:47,4.55860,0.729764,0.224972,0.049968,0.002318,2014-09-13 19:47:00
16,9/13/14 19:55,4.46460,0.742671,0.236612,0.039686,0.012152,2014-09-13 19:55:00
17,9/13/14 20:03,4.72083,0.719964,0.224486,0.060566,0.011382,2014-09-13 20:03:00
18,9/13/14 20:18,4.47290,0.708016,0.231971,0.062088,0.009520,2014-09-13 20:18:00
19,9/13/14 20:27,4.81421,0.722954,0.226816,0.045545,0.004908,2014-09-13 20:27:00
20,9/13/14 20:35,4.58972,0.715477,0.220541,0.054783,0.009497,2014-09-13 20:35:00
21,9/13/14 20:43,4.63345,0.717325,0.208483,0.064670,0.009046,2014-09-13 20:43:00
22,9/13/14 20:51,4.59768,0.697670,0.215358,0.046874,0.012505,2014-09-13 20:51:00
23,9/13/14 20:59,4.45570,0.694825,0.202789,0.052401,0.010564,2014-09-13 20:59:00
24,9/13/14 21:07,4.89321,0.709334,0.216529,0.058691,0.012774,2014-09-13 21:07:00
25,9/13/14 21:15,6.70487,0.976280,0.344037,0.099350,0.013693,2014-09-13 21:15:00
26,9/13/14 21:39,7.37721,1.113250,0.386505,0.087294,0.016271,2014-09-13 21:39:00
27,9/13/14 21:47,7.27039,1.082220,0.366399,0.079883,0.010590,2014-09-13 21:47:00
28,9/13/14 21:55,7.39930,1.121050,0.381587,0.086474,0.012381,2014-09-13 21:55:00
29,9/13/14 22:03,7.51275,1.128130,0.382217,0.081971,0.016134,2014-09-13 22:03:00
...,...,...,...,...,...,...,...
3485,10/7/14 5:15,3.86336,0.468469,0.170375,0.092328,0.012988,2014-10-07 05:15:00
3486,10/7/14 5:23,3.65903,0.440940,0.171434,0.105964,0.015694,2014-10-07 05:23:00
3487,10/7/14 5:31,3.59364,0.436908,0.179893,0.113087,0.014769,2014-10-07 05:31:00
3488,10/7/14 5:39,3.28260,0.415025,0.171286,0.117386,0.014455,2014-10-07 05:39:00
3489,10/7/14 5:47,3.49687,0.413879,0.165382,0.102418,0.015130,2014-10-07 05:47:00
3490,10/7/14 5:55,3.46249,0.410492,0.157401,0.099520,0.017553,2014-10-07 05:55:00
3491,10/7/14 6:03,3.64449,0.456510,0.176882,0.121874,0.014880,2014-10-07 06:03:00
3492,10/7/14 6:11,3.56978,0.400528,0.162680,0.089315,0.013559,2014-10-07 06:11:00
3493,10/7/14 6:19,3.54206,0.426877,0.182481,0.134379,0.014367,2014-10-07 06:19:00
3494,10/7/14 6:27,3.74740,0.439683,0.178564,0.118838,0.019787,2014-10-07 06:27:00
3495,10/7/14 6:35,3.54165,0.404511,0.156500,0.074379,0.012201,2014-10-07 06:35:00
3496,10/7/14 6:43,3.92832,0.431506,0.169920,0.090939,0.009973,2014-10-07 06:43:00
3497,10/7/14 6:51,3.71074,0.406377,0.163834,0.097348,0.010016,2014-10-07 06:51:00
3498,10/7/14 6:59,3.83711,0.436011,0.185121,0.133221,0.016204,2014-10-07 06:59:00
3499,10/7/14 7:07,3.49699,0.416138,0.170805,0.121061,0.019421,2014-10-07 07:07:00
3500,10/7/14 7:15,3.62281,0.437124,0.182971,0.149564,0.018648,2014-10-07 07:15:00
3501,10/7/14 7:23,3.47759,0.388631,0.156868,0.086987,0.011849,2014-10-07 07:23:00
3502,10/7/14 7:31,3.40688,0.360445,0.149370,0.074296,0.012681,2014-10-07 07:31:00
3503,10/7/14 7:39,3.49734,0.405758,0.176307,0.116643,0.015785,2014-10-07 07:39:00
3504,10/7/14 7:47,3.32166,0.390846,0.155536,0.092146,0.013268,2014-10-07 07:47:00
3505,10/7/14 7:55,3.48861,0.409975,0.166215,0.115080,0.015916,2014-10-07 07:55:00
3506,10/7/14 8:03,3.61874,0.395088,0.157430,0.115528,0.012686,2014-10-07 08:03:00
3507,10/7/14 8:11,3.54606,0.387418,0.149236,0.085049,0.010997,2014-10-07 08:11:00
3508,10/7/14 8:19,3.45760,0.423594,0.156946,0.085992,0.007713,2014-10-07 08:19:00
3509,10/7/14 8:27,3.46601,0.381894,0.138915,0.070869,0.008102,2014-10-07 08:27:00
3510,10/7/14 8:35,3.48122,0.414889,0.158388,0.069350,0.008544,2014-10-07 08:35:00
3511,10/7/14 8:43,3.42163,0.383357,0.152665,0.084453,0.010747,2014-10-07 08:43:00
3512,10/7/14 8:51,3.54255,0.404184,0.155790,0.091699,0.011873,2014-10-07 08:51:00
3513,10/7/14 8:59,3.54403,0.414546,0.158603,0.093408,0.009941,2014-10-07 08:59:00
3514,10/7/14 9:07,3.67001,0.408091,0.165828,0.108439,0.012156,2014-10-07 09:07:00

In [5]:
def read_tracegas(tracegas, path1, path2):
    data1 = pd.read_csv(path1, sep='\t', header=None, skiprows=1)
    data1.columns = ['datetime', tracegas]
    data1 = data1.iloc[1100341:,:]
    data2 = pd.read_csv(path2, sep='\t', header=None, skiprows=1)
    data2.columns = ['datetime', tracegas]
    data2 = data2.iloc[:551221, :]
    data = pd.concat([data1, data2])
    
    datamat = np.array(data[tracegas])
    datamat.resize((4256, 480))
    newdata = np.nanmean(datamat, axis=1)
    
    datetimemat = np.array(data['datetime'])
    datetimemat.resize((4256,480))
    newdatetime = datetimemat[:, -1]
    newdt = np.array([datetime.strptime(entry, '%Y-%m-%d %H:%M:%S') for entry in newdatetime])
    
    newdf = pd.DataFrame(columns=['datentime', tracegas])
    newdf['datentime'] = newdt
    newdf[tracegas] = newdata
    
    return newdf

In [6]:
def read_2tracegas(tracegas1, tracegas2, path1, path2, interval):
    index1 = int((1100341-1)/int(interval)+1)
    index2 = int((551221-1)/int(interval)+1)
    data1 = pd.read_csv(path1, sep='\t', header=None, skiprows=1)
    data1.columns = ['datetime', tracegas1, tracegas2]
    data1 = data1.iloc[index1:,:]
    data2 = pd.read_csv(path2, sep='\t', header=None, skiprows=1)
    data2.columns = ['datetime', tracegas1, tracegas2]
    data2 = data2.iloc[:index2, :]
    data = pd.concat([data1, data2])
    
    datamat1 = np.array(data[tracegas1])
    datamat1.resize((4256, int(480/int(interval))))
    newdata1 = np.nanmean(datamat1, axis=1)
    
    datamat2 = np.array(data[tracegas2])
    datamat2.resize((4256, int(480/int(interval))))
    newdata2 = np.nanmean(datamat2, axis=1)
    
    datetimemat = np.array(data['datetime'])
    datetimemat.resize((4256, int(480/int(interval))))
    newdatetime = datetimemat[:, -1]
    newdt = np.array([datetime.strptime(entry, '%Y-%m-%d %H:%M:%S') for entry in newdatetime])
    
    newdf = pd.DataFrame(columns=['datentime', tracegas1, tracegas2])
    newdf['datentime'] = newdt
    newdf[tracegas1] = newdata1
    newdf[tracegas2] = newdata2
    
    return newdf

In [7]:
def read_3tracegas(tracegas1, tracegas2, tracegas3, path1, path2, interval):
    index1 = int((1100341-1)/int(interval)+1)
    index2 = int((551221-1)/int(interval)+1)
    data1 = pd.read_csv(path1, sep='\t', header=None, skiprows=1)
    data1.columns = ['datetime', tracegas1, tracegas2, tracegas3]
    data1 = data1.iloc[index1:,:]
    data2 = pd.read_csv(path2, sep='\t', header=None, skiprows=1)
    data2.columns = ['datetime', tracegas1, tracegas2, tracegas3]
    data2 = data2.iloc[:index2, :]
    data = pd.concat([data1, data2])
    
    datamat1 = np.array(data[tracegas1])
    datamat1.resize((4256, int(480/int(interval))))
    newdata1 = np.nanmean(datamat1, axis=1)
    
    datamat2 = np.array(data[tracegas2])
    datamat2.resize((4256, int(480/int(interval))))
    newdata2 = np.nanmean(datamat2, axis=1)
    
    datamat3 = np.array(data[tracegas3])
    datamat3.resize((4256, int(480/int(interval))))
    newdata3 = np.nanmean(datamat3, axis=1)
    
    datetimemat = np.array(data['datetime'])
    datetimemat.resize((4256, int(480/int(interval))))
    newdatetime = datetimemat[:, -1]
    newdt = np.array([datetime.strptime(entry, '%Y-%m-%d %H:%M:%S') for entry in newdatetime])
    
    newdf = pd.DataFrame(columns=['datentime', tracegas1, tracegas2, tracegas3])
    newdf['datentime'] = newdt
    newdf[tracegas1] = newdata1
    newdf[tracegas2] = newdata2
    newdf[tracegas3] = newdata3
    
    return newdf

In [8]:
dfO3 = read_tracegas('Ozone', 'Trace_Gases-T3/9-2014_O3.txt', 'Trace_Gases-T3/10-2014_O3.txt')
dfO3

               datentime      Ozone
0    2014-09-13 17:47:00  66.524375
1    2014-09-13 17:55:00  61.587474
2    2014-09-13 18:03:00  49.494781
3    2014-09-13 18:11:00  50.088125
4    2014-09-13 18:19:00  50.118580
5    2014-09-13 18:27:00  45.937292
6    2014-09-13 18:35:00  37.641458
7    2014-09-13 18:43:00  34.505010
8    2014-09-13 18:51:00  38.534167
9    2014-09-13 18:59:00  45.923125
10   2014-09-13 19:07:00  44.671339
11   2014-09-13 19:15:00  40.412500
12   2014-09-13 19:23:00  37.465971
13   2014-09-13 19:31:00  36.526514
14   2014-09-13 19:39:00  33.351042
15   2014-09-13 19:47:00  30.068958
16   2014-09-13 19:55:00  29.719874
17   2014-09-13 20:03:00  24.106263
18   2014-09-13 20:11:00  22.872083
19   2014-09-13 20:19:00  22.887474
20   2014-09-13 20:27:00  17.889583
21   2014-09-13 20:35:00  16.370000
22   2014-09-13 20:43:00  14.955230
23   2014-09-13 20:51:00  12.166667
24   2014-09-13 20:59:00  12.136667
25   2014-09-13 21:07:00  11.982636
26   2014-09-13 21:15:00  15.215833
27   2014-09-13 21:23:00  21.604393
28   2014-09-13 21:31:00  21.653653
29   2014-09-13 21:39:00  22.937996
...                  ...        ...
4226 2014-10-07 05:15:00   6.170833
4227 2014-10-07 05:23:00   8.608577
4228 2014-10-07 05:31:00  10.200625
4229 2014-10-07 05:39:00   6.592083
4230 2014-10-07 05:47:00   5.712735
4231 2014-10-07 05:55:00   3.538542
4232 2014-10-07 06:03:00   4.097500
4233 2014-10-07 06:11:00   7.181799
4234 2014-10-07 06:19:00   6.524426
4235 2014-10-07 06:27:00   3.706667
4236 2014-10-07 06:35:00   2.888494
4237 2014-10-07 06:43:00   3.860208
4238 2014-10-07 06:51:00   3.268333
4239 2014-10-07 06:59:00   3.878452
4240 2014-10-07 07:07:00   2.124843
4241 2014-10-07 07:15:00   2.884167
4242 2014-10-07 07:23:00   2.160625
4243 2014-10-07 07:31:00   2.214614
4244 2014-10-07 07:39:00   2.317708
4245 2014-10-07 07:47:00   0.886458
4246 2014-10-07 07:55:00   1.077083
4247 2014-10-07 08:03:00   0.726096
4248 2014-10-07 08:11:00   0.659167
4249 2014-10-07 08:19:00   0.845720
4250 2014-10-07 08:27:00   0.715449
4251 2014-10-07 08:35:00   1.118958
4252 2014-10-07 08:43:00   0.873958
4253 2014-10-07 08:51:00   1.552083
4254 2014-10-07 08:59:00   1.745511
4255 2014-10-07 09:07:00   2.468267

[4256 rows x 2 columns]

In [9]:
newdf = pd.merge(df, dfO3, how='left', on=['datentime'])
newdf

,Time stop,Organic,Sulfate,Ammonium,Nitrate,Chloride,datentime,Ozone
0,9/13/14 17:47,11.94720,1.758410,0.550953,0.290176,0.015616,2014-09-13 17:47:00,66.524375
1,9/13/14 17:55,11.20270,1.590140,0.515114,0.211021,0.013689,2014-09-13 17:55:00,61.587474
2,9/13/14 18:03,10.73810,1.484200,0.456858,0.174378,0.014700,2014-09-13 18:03:00,49.494781
3,9/13/14 18:11,11.26250,1.562690,0.477693,0.174844,0.017399,2014-09-13 18:11:00,50.088125
4,9/13/14 18:19,11.69100,1.582690,0.503957,0.194480,0.016549,2014-09-13 18:19:00,50.118580
5,9/13/14 18:27,11.38780,1.580270,0.510905,0.164823,0.018170,2014-09-13 18:27:00,45.937292
6,9/13/14 18:35,10.95210,1.450210,0.453779,0.162619,0.008872,2014-09-13 18:35:00,37.641458
7,9/13/14 18:43,10.92600,1.433650,0.476453,0.152684,0.016209,2014-09-13 18:43:00,34.505010
8,9/13/14 18:51,3.88525,0.595637,0.171677,0.038497,0.009524,2014-09-13 18:51:00,38.534167
9,9/13/14 18:59,3.55995,0.596208,0.174129,0.047259,0.009437,2014-09-13 18:59:00,45.923125
10,9/13/14 19:07,5.94130,0.900445,0.284233,0.046628,0.010277,2014-09-13 19:07:00,44.671339
11,9/13/14 19:15,5.81877,0.900757,0.275290,0.082913,0.009717,2014-09-13 19:15:00,40.412500
12,9/13/14 19:23,4.63620,0.753188,0.230268,0.043465,0.008388,2014-09-13 19:23:00,37.465971
13,9/13/14 19:31,4.92573,0.777560,0.259077,0.071588,0.011794,2014-09-13 19:31:00,36.526514
14,9/13/14 19:39,4.74542,0.735238,0.239229,0.055658,0.008778,2014-09-13 19:39:00,33.351042
15,9/13/14 19:47,4.55860,0.729764,0.224972,0.049968,0.002318,2014-09-13 19:47:00,30.068958
16,9/13/14 19:55,4.46460,0.742671,0.236612,0.039686,0.012152,2014-09-13 19:55:00,29.719874
17,9/13/14 20:03,4.72083,0.719964,0.224486,0.060566,0.011382,2014-09-13 20:03:00,24.106263
18,9/13/14 20:18,4.47290,0.708016,0.231971,0.062088,0.009520,2014-09-13 20:18:00,NaN
19,9/13/14 20:27,4.81421,0.722954,0.226816,0.045545,0.004908,2014-09-13 20:27:00,17.889583
20,9/13/14 20:35,4.58972,0.715477,0.220541,0.054783,0.009497,2014-09-13 20:35:00,16.370000
21,9/13/14 20:43,4.63345,0.717325,0.208483,0.064670,0.009046,2014-09-13 20:43:00,14.955230
22,9/13/14 20:51,4.59768,0.697670,0.215358,0.046874,0.012505,2014-09-13 20:51:00,12.166667
23,9/13/14 20:59,4.45570,0.694825,0.202789,0.052401,0.010564,2014-09-13 20:59:00,12.136667
24,9/13/14 21:07,4.89321,0.709334,0.216529,0.058691,0.012774,2014-09-13 21:07:00,11.982636
25,9/13/14 21:15,6.70487,0.976280,0.344037,0.099350,0.013693,2014-09-13 21:15:00,15.215833
26,9/13/14 21:39,7.37721,1.113250,0.386505,0.087294,0.016271,2014-09-13 21:39:00,22.937996
27,9/13/14 21:47,7.27039,1.082220,0.366399,0.079883,0.010590,2014-09-13 21:47:00,23.530417
28,9/13/14 21:55,7.39930,1.121050,0.381587,0.086474,0.012381,2014-09-13 21:55:00,26.245188
29,9/13/14 22:03,7.51275,1.128130,0.382217,0.081971,0.016134,2014-09-13 22:03:00,28.223690
...,...,...,...,...,...,...,...,...
3485,10/7/14 5:15,3.86336,0.468469,0.170375,0.092328,0.012988,2014-10-07 05:15:00,6.170833
3486,10/7/14 5:23,3.65903,0.440940,0.171434,0.105964,0.015694,2014-10-07 05:23:00,8.608577
3487,10/7/14 5:31,3.59364,0.436908,0.179893,0.113087,0.014769,2014-10-07 05:31:00,10.200625
3488,10/7/14 5:39,3.28260,0.415025,0.171286,0.117386,0.014455,2014-10-07 05:39:00,6.592083
3489,10/7/14 5:47,3.49687,0.413879,0.165382,0.102418,0.015130,2014-10-07 05:47:00,5.712735
3490,10/7/14 5:55,3.46249,0.410492,0.157401,0.099520,0.017553,2014-10-07 05:55:00,3.538542
3491,10/7/14 6:03,3.64449,0.456510,0.176882,0.121874,0.014880,2014-10-07 06:03:00,4.097500
3492,10/7/14 6:11,3.56978,0.400528,0.162680,0.089315,0.013559,2014-10-07 06:11:00,7.181799
3493,10/7/14 6:19,3.54206,0.426877,0.182481,0.134379,0.014367,2014-10-07 06:19:00,6.524426
3494,10/7/14 6:27,3.74740,0.439683,0.178564,0.118838,0.019787,2014-10-07 06:27:00,3.706667
3495,10/7/14 6:35,3.54165,0.404511,0.156500,0.074379,0.012201,2014-10-07 06:35:00,2.888494
3496,10/7/14 6:43,3.92832,0.431506,0.169920,0.090939,0.009973,2014-10-07 06:43:00,3.860208
3497,10/7/14 6:51,3.71074,0.406377,0.163834,0.097348,0.010016,2014-10-07 06:51:00,3.268333
3498,10/7/14 6:59,3.83711,0.436011,0.185121,0.133221,0.016204,2014-10-07 06:59:00,3.878452
3499,10/7/14 7:07,3.49699,0.416138,0.170805,0.121061,0.019421,2014-10-07 07:07:00,2.124843
3500,10/7/14 7:15,3.62281,0.437124,0.182971,0.149564,0.018648,2014-10-07 07:15:00,2.884167
3501,10/7/14 7:23,3.47759,0.388631,0.156868,0.086987,0.011849,2014-10-07 07:23:00,2.160625
3502,10/7/14 7:31,3.40688,0.360445,0.149370,0.074296,0.012681,2014-10-07 07:31:00,2.214614
3503,10/7/14 7:39,3.49734,0.405758,0.176307,0.116643,0.015785,2014-10-07 07:39:00,2.317708
3504,10/7/14 7:47,3.32166,0.390846,0.155536,0.092146,0.013268,2014-10-07 07:47:00,0.886458
3505,10/7/14 7:55,3.48861,0.409975,0.166215,0.115080,0.015916,2014-10-07 07:55:00,1.077083
3506,10/7/14 8:03,3.61874,0.395088,0.157430,0.115528,0.012686,2014-10-07 08:03:00,0.726096
3507,10/7/14 8:11,3.54606,0.387418,0.149236,0.085049,0.010997,2014-10-07 08:11:00,0.659167
3508,10/7/14 8:19,3.45760,0.423594,0.156946,0.085992,0.007713,2014-10-07 08:19:00,0.845720
3509,10/7/14 8:27,3.46601,0.381894,0.138915,0.070869,0.008102,2014-10-07 08:27:00,0.715449
3510,10/7/14 8:35,3.48122,0.414889,0.158388,0.069350,0.008544,2014-10-07 08:35:00,1.118958
3511,10/7/14 8:43,3.42163,0.383357,0.152665,0.084453,0.010747,2014-10-07 08:43:00,0.873958
3512,10/7/14 8:51,3.54255,0.404184,0.155790,0.091699,0.011873,2014-10-07 08:51:00,1.552083
3513,10/7/14 8:59,3.54403,0.414546,0.158603,0.093408,0.009941,2014-10-07 08:59:00,1.745511
3514,10/7/14 9:07,3.67001,0.408091,0.165828,0.108439,0.012156,2014-10-07 09:07:00,2.468267

In [10]:
dfCON2OH2O = read_3tracegas('CO', 'N2O', 'H2O', 'Trace_Gases-T3/9-2014_CO.txt', 'Trace_Gases-T3/10-2014_CO.txt', 1)
dfCON2OH2O

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: RuntimeWarning: Mean of empty slice

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:18: RuntimeWarning: Mean of empty slice
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:22: RuntimeWarning: Mean of empty slice

               datentime        CO       N2O           H2O
0    2014-09-13 17:47:00  0.178201  0.307698  30919.728814
1    2014-09-13 17:55:00  0.174315  0.307689  31046.698312
2    2014-09-13 18:03:00  0.157262  0.307984  29523.415254
3    2014-09-13 18:11:00  0.157871  0.307962  29601.052854
4    2014-09-13 18:19:00  0.163030  0.307179  31677.964059
5    2014-09-13 18:27:00  0.161223  0.306634  32611.820296
6    2014-09-13 18:35:00  0.150850  0.306826  31608.273305
7    2014-09-13 18:43:00  0.150003  0.306567  32419.156780
8    2014-09-13 18:51:00  0.133811  0.307636  28294.280591
9    2014-09-13 18:59:00  0.125564  0.308413  24998.076271
10   2014-09-13 19:07:00  0.127440  0.308005  25315.139831
11   2014-09-13 19:15:00  0.132527  0.306779  27501.997886
12   2014-09-13 19:23:00  0.129414  0.306801  27917.350951
13   2014-09-13 19:31:00  0.130256  0.306816  28031.723992
14   2014-09-13 19:39:00  0.130023  0.306406  29104.974630
15   2014-09-13 19:47:00  0.135835  0.306392  29037.695560
16   2014-09-13 19:55:00  0.129636  0.306504  28853.359408
17   2014-09-13 20:03:00  0.131238  0.306206  29710.691332
18   2014-09-13 20:11:00  0.131555  0.306233  29769.202960
19   2014-09-13 20:19:00  0.131982  0.306060  29909.163136
20   2014-09-13 20:27:00  0.134608  0.306041  30764.598726
21   2014-09-13 20:35:00  0.135521  0.305811  30975.292373
22   2014-09-13 20:43:00  0.136636  0.305816  31040.696203
23   2014-09-13 20:51:00  0.136587  0.305498  31582.762208
24   2014-09-13 20:59:00  0.138346  0.305749  31431.852008
25   2014-09-13 21:07:00  0.136948  0.305989  31692.137712
26   2014-09-13 21:15:00  0.141294  0.306334  31566.287526
27   2014-09-13 21:23:00  0.152066  0.306808  30885.788136
28   2014-09-13 21:31:00  0.153470  0.307036  30705.173362
29   2014-09-13 21:39:00  0.148556  0.306925  30526.359408
...                  ...       ...       ...           ...
4226 2014-10-07 05:15:00  0.261465       NaN           NaN
4227 2014-10-07 05:23:00  0.257929       NaN           NaN
4228 2014-10-07 05:31:00  0.254193       NaN           NaN
4229 2014-10-07 05:39:00  0.251781       NaN           NaN
4230 2014-10-07 05:47:00  0.250623       NaN           NaN
4231 2014-10-07 05:55:00  0.251262       NaN           NaN
4232 2014-10-07 06:03:00  0.251758       NaN           NaN
4233 2014-10-07 06:11:00  0.255634       NaN           NaN
4234 2014-10-07 06:19:00  0.259452       NaN           NaN
4235 2014-10-07 06:27:00  0.260420       NaN           NaN
4236 2014-10-07 06:35:00  0.263080       NaN           NaN
4237 2014-10-07 06:43:00  0.269827       NaN           NaN
4238 2014-10-07 06:51:00  0.276950       NaN           NaN
4239 2014-10-07 06:59:00  0.275092       NaN           NaN
4240 2014-10-07 07:07:00  0.272896       NaN           NaN
4241 2014-10-07 07:15:00  0.271321       NaN           NaN
4242 2014-10-07 07:23:00  0.269548       NaN           NaN
4243 2014-10-07 07:31:00  0.270346       NaN           NaN
4244 2014-10-07 07:39:00  0.268689       NaN           NaN
4245 2014-10-07 07:47:00  0.268921       NaN           NaN
4246 2014-10-07 07:55:00  0.270000       NaN           NaN
4247 2014-10-07 08:03:00  0.272174       NaN           NaN
4248 2014-10-07 08:11:00  0.273319       NaN           NaN
4249 2014-10-07 08:19:00  0.274787       NaN           NaN
4250 2014-10-07 08:27:00  0.274747       NaN           NaN
4251 2014-10-07 08:35:00  0.272492       NaN           NaN
4252 2014-10-07 08:43:00  0.273140       NaN           NaN
4253 2014-10-07 08:51:00  0.272416       NaN           NaN
4254 2014-10-07 08:59:00  0.272832       NaN           NaN
4255 2014-10-07 09:07:00  0.271029       NaN           NaN

[4256 rows x 4 columns]

In [11]:
newdf = pd.merge(newdf, dfCON2OH2O, how='left', on=['datentime'])
newdf

,Time stop,Organic,Sulfate,Ammonium,Nitrate,Chloride,datentime,Ozone,CO,N2O,H2O
0,9/13/14 17:47,11.94720,1.758410,0.550953,0.290176,0.015616,2014-09-13 17:47:00,66.524375,0.178201,0.307698,30919.728814
1,9/13/14 17:55,11.20270,1.590140,0.515114,0.211021,0.013689,2014-09-13 17:55:00,61.587474,0.174315,0.307689,31046.698312
2,9/13/14 18:03,10.73810,1.484200,0.456858,0.174378,0.014700,2014-09-13 18:03:00,49.494781,0.157262,0.307984,29523.415254
3,9/13/14 18:11,11.26250,1.562690,0.477693,0.174844,0.017399,2014-09-13 18:11:00,50.088125,0.157871,0.307962,29601.052854
4,9/13/14 18:19,11.69100,1.582690,0.503957,0.194480,0.016549,2014-09-13 18:19:00,50.118580,0.163030,0.307179,31677.964059
5,9/13/14 18:27,11.38780,1.580270,0.510905,0.164823,0.018170,2014-09-13 18:27:00,45.937292,0.161223,0.306634,32611.820296
6,9/13/14 18:35,10.95210,1.450210,0.453779,0.162619,0.008872,2014-09-13 18:35:00,37.641458,0.150850,0.306826,31608.273305
7,9/13/14 18:43,10.92600,1.433650,0.476453,0.152684,0.016209,2014-09-13 18:43:00,34.505010,0.150003,0.306567,32419.156780
8,9/13/14 18:51,3.88525,0.595637,0.171677,0.038497,0.009524,2014-09-13 18:51:00,38.534167,0.133811,0.307636,28294.280591
9,9/13/14 18:59,3.55995,0.596208,0.174129,0.047259,0.009437,2014-09-13 18:59:00,45.923125,0.125564,0.308413,24998.076271
10,9/13/14 19:07,5.94130,0.900445,0.284233,0.046628,0.010277,2014-09-13 19:07:00,44.671339,0.127440,0.308005,25315.139831
11,9/13/14 19:15,5.81877,0.900757,0.275290,0.082913,0.009717,2014-09-13 19:15:00,40.412500,0.132527,0.306779,27501.997886
12,9/13/14 19:23,4.63620,0.753188,0.230268,0.043465,0.008388,2014-09-13 19:23:00,37.465971,0.129414,0.306801,27917.350951
13,9/13/14 19:31,4.92573,0.777560,0.259077,0.071588,0.011794,2014-09-13 19:31:00,36.526514,0.130256,0.306816,28031.723992
14,9/13/14 19:39,4.74542,0.735238,0.239229,0.055658,0.008778,2014-09-13 19:39:00,33.351042,0.130023,0.306406,29104.974630
15,9/13/14 19:47,4.55860,0.729764,0.224972,0.049968,0.002318,2014-09-13 19:47:00,30.068958,0.135835,0.306392,29037.695560
16,9/13/14 19:55,4.46460,0.742671,0.236612,0.039686,0.012152,2014-09-13 19:55:00,29.719874,0.129636,0.306504,28853.359408
17,9/13/14 20:03,4.72083,0.719964,0.224486,0.060566,0.011382,2014-09-13 20:03:00,24.106263,0.131238,0.306206,29710.691332
18,9/13/14 20:18,4.47290,0.708016,0.231971,0.062088,0.009520,2014-09-13 20:18:00,NaN,NaN,NaN,NaN
19,9/13/14 20:27,4.81421,0.722954,0.226816,0.045545,0.004908,2014-09-13 20:27:00,17.889583,0.134608,0.306041,30764.598726
20,9/13/14 20:35,4.58972,0.715477,0.220541,0.054783,0.009497,2014-09-13 20:35:00,16.370000,0.135521,0.305811,30975.292373
21,9/13/14 20:43,4.63345,0.717325,0.208483,0.064670,0.009046,2014-09-13 20:43:00,14.955230,0.136636,0.305816,31040.696203
22,9/13/14 20:51,4.59768,0.697670,0.215358,0.046874,0.012505,2014-09-13 20:51:00,12.166667,0.136587,0.305498,31582.762208
23,9/13/14 20:59,4.45570,0.694825,0.202789,0.052401,0.010564,2014-09-13 20:59:00,12.136667,0.138346,0.305749,31431.852008
24,9/13/14 21:07,4.89321,0.709334,0.216529,0.058691,0.012774,2014-09-13 21:07:00,11.982636,0.136948,0.305989,31692.137712
25,9/13/14 21:15,6.70487,0.976280,0.344037,0.099350,0.013693,2014-09-13 21:15:00,15.215833,0.141294,0.306334,31566.287526
26,9/13/14 21:39,7.37721,1.113250,0.386505,0.087294,0.016271,2014-09-13 21:39:00,22.937996,0.148556,0.306925,30526.359408
27,9/13/14 21:47,7.27039,1.082220,0.366399,0.079883,0.010590,2014-09-13 21:47:00,23.530417,0.144452,0.306950,30330.042373
28,9/13/14 21:55,7.39930,1.121050,0.381587,0.086474,0.012381,2014-09-13 21:55:00,26.245188,0.143281,0.307129,29860.452431
29,9/13/14 22:03,7.51275,1.128130,0.382217,0.081971,0.016134,2014-09-13 22:03:00,28.223690,0.142224,0.307397,29550.672304
...,...,...,...,...,...,...,...,...,...,...,...
3485,10/7/14 5:15,3.86336,0.468469,0.170375,0.092328,0.012988,2014-10-07 05:15:00,6.170833,0.261465,NaN,NaN
3486,10/7/14 5:23,3.65903,0.440940,0.171434,0.105964,0.015694,2014-10-07 05:23:00,8.608577,0.257929,NaN,NaN
3487,10/7/14 5:31,3.59364,0.436908,0.179893,0.113087,0.014769,2014-10-07 05:31:00,10.200625,0.254193,NaN,NaN
3488,10/7/14 5:39,3.28260,0.415025,0.171286,0.117386,0.014455,2014-10-07 05:39:00,6.592083,0.251781,NaN,NaN
3489,10/7/14 5:47,3.49687,0.413879,0.165382,0.102418,0.015130,2014-10-07 05:47:00,5.712735,0.250623,NaN,NaN
3490,10/7/14 5:55,3.46249,0.410492,0.157401,0.099520,0.017553,2014-10-07 05:55:00,3.538542,0.251262,NaN,NaN
3491,10/7/14 6:03,3.64449,0.456510,0.176882,0.121874,0.014880,2014-10-07 06:03:00,4.097500,0.251758,NaN,NaN
3492,10/7/14 6:11,3.56978,0.400528,0.162680,0.089315,0.013559,2014-10-07 06:11:00,7.181799,0.255634,NaN,NaN
3493,10/7/14 6:19,3.54206,0.426877,0.182481,0.134379,0.014367,2014-10-07 06:19:00,6.524426,0.259452,NaN,NaN
3494,10/7/14 6:27,3.74740,0.439683,0.178564,0.118838,0.019787,2014-10-07 06:27:00,3.706667,0.260420,NaN,NaN
3495,10/7/14 6:35,3.54165,0.404511,0.156500,0.074379,0.012201,2014-10-07 06:35:00,2.888494,0.263080,NaN,NaN
3496,10/7/14 6:43,3.92832,0.431506,0.169920,0.090939,0.009973,2014-10-07 06:43:00,3.860208,0.269827,NaN,NaN
3497,10/7/14 6:51,3.71074,0.406377,0.163834,0.097348,0.010016,2014-10-07 06:51:00,3.268333,0.276950,NaN,NaN
3498,10/7/14 6:59,3.83711,0.436011,0.185121,0.133221,0.016204,2014-10-07 06:59:00,3.878452,0.275092,NaN,NaN
3499,10/7/14 7:07,3.49699,0.416138,0.170805,0.121061,0.019421,2014-10-07 07:07:00,2.124843,0.272896,NaN,NaN
3500,10/7/14 7:15,3.62281,0.437124,0.182971,0.149564,0.018648,2014-10-07 07:15:00,2.884167,0.271321,NaN,NaN
3501,10/7/14 7:23,3.47759,0.388631,0.156868,0.086987,0.011849,2014-10-07 07:23:00,2.160625,0.269548,NaN,NaN
3502,10/7/14 7:31,3.40688,0.360445,0.149370,0.074296,0.012681,2014-10-07 07:31:00,2.214614,0.270346,NaN,NaN
3503,10/7/14 7:39,3.49734,0.405758,0.176307,0.116643,0.015785,2014-10-07 07:39:00,2.317708,0.268689,NaN,NaN
3504,10/7/14 7:47,3.32166,0.390846,0.155536,0.092146,0.013268,2014-10-07 07:47:00,0.886458,0.268921,NaN,NaN
3505,10/7/14 7:55,3.48861,0.409975,0.166215,0.115080,0.015916,2014-10-07 07:55:00,1.077083,0.270000,NaN,NaN
3506,10/7/14 8:03,3.61874,0.395088,0.157430,0.115528,0.012686,2014-10-07 08:03:00,0.726096,0.272174,NaN,NaN
3507,10/7/14 8:11,3.54606,0.387418,0.149236,0.085049,0.010997,2014-10-07 08:11:00,0.659167,0.273319,NaN,NaN
3508,10/7/14 8:19,3.45760,0.423594,0.156946,0.085992,0.007713,2014-10-07 08:19:00,0.845720,0.274787,NaN,NaN
3509,10/7/14 8:27,3.46601,0.381894,0.138915,0.070869,0.008102,2014-10-07 08:27:00,0.715449,0.274747,NaN,NaN
3510,10/7/14 8:35,3.48122,0.414889,0.158388,0.069350,0.008544,2014-10-07 08:35:00,1.118958,0.272492,NaN,NaN
3511,10/7/14 8:43,3.42163,0.383357,0.152665,0.084453,0.010747,2014-10-07 08:43:00,0.873958,0.273140,NaN,NaN
3512,10/7/14 8:51,3.54255,0.404184,0.155790,0.091699,0.011873,2014-10-07 08:51:00,1.552083,0.272416,NaN,NaN
3513,10/7/14 8:59,3.54403,0.414546,0.158603,0.093408,0.009941,2014-10-07 08:59:00,1.745511,0.272832,NaN,NaN
3514,10/7/14 9:07,3.67001,0.408091,0.165828,0.108439,0.012156,2014-10-07 09:07:00,2.468267,0.271029,NaN,NaN

In [12]:
dfNOx = read_3tracegas('NO', 'NO2', 'NOy', 'Trace_Gases-T3/9-2014_NOx.txt', 'Trace_Gases-T3/10-2014_NOx.txt', 10)
dfNOx

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: RuntimeWarning: Mean of empty slice

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:18: RuntimeWarning: Mean of empty slice
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:22: RuntimeWarning: Mean of empty slice

               datentime        NO       NO2       NOy
0    2014-09-13 17:47:00 -0.028833  1.063667  3.284333
1    2014-09-13 17:55:00 -0.042333  0.995333  3.094375
2    2014-09-13 18:03:00 -0.032667  0.735583  2.211396
3    2014-09-13 18:11:00 -0.036000  0.749917  2.296271
4    2014-09-13 18:19:00 -0.023917  0.832750  2.538750
5    2014-09-13 18:27:00 -0.016250  0.843917  2.262146
6    2014-09-13 18:35:00 -0.008750  0.665500  1.659854
7    2014-09-13 18:43:00  0.000917  0.743917  1.641729
8    2014-09-13 18:51:00 -0.000333  0.456000  1.183208
9    2014-09-13 18:59:00 -0.079750  0.537167  1.054812
10   2014-09-13 19:07:00 -0.071250  0.522083  1.047417
11   2014-09-13 19:15:00 -0.036167  0.540833  1.058500
12   2014-09-13 19:23:00 -0.048417  0.716250  1.243521
13   2014-09-13 19:31:00  0.013417  0.812750  1.307521
14   2014-09-13 19:39:00 -0.048583  1.033250  1.521208
15   2014-09-13 19:47:00  0.012583  1.094500  1.588146
16   2014-09-13 19:55:00 -0.021500  1.026417  1.484417
17   2014-09-13 20:03:00 -0.002000  0.816833  1.228563
18   2014-09-13 20:11:00  0.040917  0.792500  1.244833
19   2014-09-13 20:19:00  0.021083  0.846833  1.293854
20   2014-09-13 20:27:00  0.533500  0.237667  2.050938
21   2014-09-13 20:35:00  0.025083  0.863083  1.205896
22   2014-09-13 20:43:00  0.042083  0.735333  1.129646
23   2014-09-13 20:51:00  0.017917  0.879667  1.212104
24   2014-09-13 20:59:00  0.039583  1.009667  1.327479
25   2014-09-13 21:07:00  0.026667  0.956167  1.335771
26   2014-09-13 21:15:00  0.014417  0.838167  1.182333
27   2014-09-13 21:23:00 -0.024333  0.960750  1.349458
28   2014-09-13 21:31:00 -0.002917  0.994833  1.416938
29   2014-09-13 21:39:00 -0.046583  1.042750  1.366854
...                  ...       ...       ...       ...
4226 2014-10-07 05:15:00  0.049667  2.976083  2.880062
4227 2014-10-07 05:23:00  0.025250  2.319750  2.271542
4228 2014-10-07 05:31:00  0.002833  1.920083  1.866646
4229 2014-10-07 05:39:00  0.005833  2.603417  2.488187
4230 2014-10-07 05:47:00 -0.011500  2.676917  2.524917
4231 2014-10-07 05:55:00  0.683083  2.594667  3.326354
4232 2014-10-07 06:03:00  0.309333  3.120857  3.183536
4233 2014-10-07 06:11:00       NaN       NaN       NaN
4234 2014-10-07 06:19:00       NaN       NaN       NaN
4235 2014-10-07 06:27:00       NaN       NaN       NaN
4236 2014-10-07 06:35:00       NaN       NaN       NaN
4237 2014-10-07 06:43:00       NaN       NaN       NaN
4238 2014-10-07 06:51:00       NaN       NaN       NaN
4239 2014-10-07 06:59:00       NaN       NaN       NaN
4240 2014-10-07 07:07:00  1.014667  2.901000       NaN
4241 2014-10-07 07:15:00  0.032417  3.230083       NaN
4242 2014-10-07 07:23:00  0.854750  3.338250       NaN
4243 2014-10-07 07:31:00  0.153583  3.374000       NaN
4244 2014-10-07 07:39:00  1.057667  3.211750       NaN
4245 2014-10-07 07:47:00  3.134167  2.345000       NaN
4246 2014-10-07 07:55:00  0.657167  3.264583       NaN
4247 2014-10-07 08:03:00  3.502583  2.459917       NaN
4248 2014-10-07 08:11:00  2.455583  2.677167  4.175158
4249 2014-10-07 08:19:00  1.824417  2.496917  4.153479
4250 2014-10-07 08:27:00  1.212333  2.773333  3.760437
4251 2014-10-07 08:35:00  0.822750  2.806250  3.349333
4252 2014-10-07 08:43:00  0.732917  2.386917  3.085583
4253 2014-10-07 08:51:00  0.397083  2.285917  2.622875
4254 2014-10-07 08:59:00  0.454417  2.227750  2.524521
4255 2014-10-07 09:07:00  0.808333  2.414167  3.063438

[4256 rows x 4 columns]

In [13]:
newdf = pd.merge(newdf, dfNOx, how='left', on=['datentime'])
newdf

,Time stop,Organic,Sulfate,Ammonium,Nitrate,Chloride,datentime,Ozone,CO,N2O,H2O,NO,NO2,NOy
0,9/13/14 17:47,11.94720,1.758410,0.550953,0.290176,0.015616,2014-09-13 17:47:00,66.524375,0.178201,0.307698,30919.728814,-0.028833,1.063667,3.284333
1,9/13/14 17:55,11.20270,1.590140,0.515114,0.211021,0.013689,2014-09-13 17:55:00,61.587474,0.174315,0.307689,31046.698312,-0.042333,0.995333,3.094375
2,9/13/14 18:03,10.73810,1.484200,0.456858,0.174378,0.014700,2014-09-13 18:03:00,49.494781,0.157262,0.307984,29523.415254,-0.032667,0.735583,2.211396
3,9/13/14 18:11,11.26250,1.562690,0.477693,0.174844,0.017399,2014-09-13 18:11:00,50.088125,0.157871,0.307962,29601.052854,-0.036000,0.749917,2.296271
4,9/13/14 18:19,11.69100,1.582690,0.503957,0.194480,0.016549,2014-09-13 18:19:00,50.118580,0.163030,0.307179,31677.964059,-0.023917,0.832750,2.538750
5,9/13/14 18:27,11.38780,1.580270,0.510905,0.164823,0.018170,2014-09-13 18:27:00,45.937292,0.161223,0.306634,32611.820296,-0.016250,0.843917,2.262146
6,9/13/14 18:35,10.95210,1.450210,0.453779,0.162619,0.008872,2014-09-13 18:35:00,37.641458,0.150850,0.306826,31608.273305,-0.008750,0.665500,1.659854
7,9/13/14 18:43,10.92600,1.433650,0.476453,0.152684,0.016209,2014-09-13 18:43:00,34.505010,0.150003,0.306567,32419.156780,0.000917,0.743917,1.641729
8,9/13/14 18:51,3.88525,0.595637,0.171677,0.038497,0.009524,2014-09-13 18:51:00,38.534167,0.133811,0.307636,28294.280591,-0.000333,0.456000,1.183208
9,9/13/14 18:59,3.55995,0.596208,0.174129,0.047259,0.009437,2014-09-13 18:59:00,45.923125,0.125564,0.308413,24998.076271,-0.079750,0.537167,1.054812
10,9/13/14 19:07,5.94130,0.900445,0.284233,0.046628,0.010277,2014-09-13 19:07:00,44.671339,0.127440,0.308005,25315.139831,-0.071250,0.522083,1.047417
11,9/13/14 19:15,5.81877,0.900757,0.275290,0.082913,0.009717,2014-09-13 19:15:00,40.412500,0.132527,0.306779,27501.997886,-0.036167,0.540833,1.058500
12,9/13/14 19:23,4.63620,0.753188,0.230268,0.043465,0.008388,2014-09-13 19:23:00,37.465971,0.129414,0.306801,27917.350951,-0.048417,0.716250,1.243521
13,9/13/14 19:31,4.92573,0.777560,0.259077,0.071588,0.011794,2014-09-13 19:31:00,36.526514,0.130256,0.306816,28031.723992,0.013417,0.812750,1.307521
14,9/13/14 19:39,4.74542,0.735238,0.239229,0.055658,0.008778,2014-09-13 19:39:00,33.351042,0.130023,0.306406,29104.974630,-0.048583,1.033250,1.521208
15,9/13/14 19:47,4.55860,0.729764,0.224972,0.049968,0.002318,2014-09-13 19:47:00,30.068958,0.135835,0.306392,29037.695560,0.012583,1.094500,1.588146
16,9/13/14 19:55,4.46460,0.742671,0.236612,0.039686,0.012152,2014-09-13 19:55:00,29.719874,0.129636,0.306504,28853.359408,-0.021500,1.026417,1.484417
17,9/13/14 20:03,4.72083,0.719964,0.224486,0.060566,0.011382,2014-09-13 20:03:00,24.106263,0.131238,0.306206,29710.691332,-0.002000,0.816833,1.228563
18,9/13/14 20:18,4.47290,0.708016,0.231971,0.062088,0.009520,2014-09-13 20:18:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,9/13/14 20:27,4.81421,0.722954,0.226816,0.045545,0.004908,2014-09-13 20:27:00,17.889583,0.134608,0.306041,30764.598726,0.533500,0.237667,2.050938
20,9/13/14 20:35,4.58972,0.715477,0.220541,0.054783,0.009497,2014-09-13 20:35:00,16.370000,0.135521,0.305811,30975.292373,0.025083,0.863083,1.205896
21,9/13/14 20:43,4.63345,0.717325,0.208483,0.064670,0.009046,2014-09-13 20:43:00,14.955230,0.136636,0.305816,31040.696203,0.042083,0.735333,1.129646
22,9/13/14 20:51,4.59768,0.697670,0.215358,0.046874,0.012505,2014-09-13 20:51:00,12.166667,0.136587,0.305498,31582.762208,0.017917,0.879667,1.212104
23,9/13/14 20:59,4.45570,0.694825,0.202789,0.052401,0.010564,2014-09-13 20:59:00,12.136667,0.138346,0.305749,31431.852008,0.039583,1.009667,1.327479
24,9/13/14 21:07,4.89321,0.709334,0.216529,0.058691,0.012774,2014-09-13 21:07:00,11.982636,0.136948,0.305989,31692.137712,0.026667,0.956167,1.335771
25,9/13/14 21:15,6.70487,0.976280,0.344037,0.099350,0.013693,2014-09-13 21:15:00,15.215833,0.141294,0.306334,31566.287526,0.014417,0.838167,1.182333
26,9/13/14 21:39,7.37721,1.113250,0.386505,0.087294,0.016271,2014-09-13 21:39:00,22.937996,0.148556,0.306925,30526.359408,-0.046583,1.042750,1.366854
27,9/13/14 21:47,7.27039,1.082220,0.366399,0.079883,0.010590,2014-09-13 21:47:00,23.530417,0.144452,0.306950,30330.042373,-0.035333,0.900750,1.304292
28,9/13/14 21:55,7.39930,1.121050,0.381587,0.086474,0.012381,2014-09-13 21:55:00,26.245188,0.143281,0.307129,29860.452431,-0.029500,0.955833,1.384292
29,9/13/14 22:03,7.51275,1.128130,0.382217,0.081971,0.016134,2014-09-13 22:03:00,28.223690,0.142224,0.307397,29550.672304,-0.042667,0.861833,1.369083
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3485,10/7/14 5:15,3.86336,0.468469,0.170375,0.092328,0.012988,2014-10-07 05:15:00,6.170833,0.261465,NaN,NaN,0.049667,2.976083,2.880062
3486,10/7/14 5:23,3.65903,0.440940,0.171434,0.105964,0.015694,2014-10-07 05:23:00,8.608577,0.257929,NaN,NaN,0.025250,2.319750,2.271542
3487,10/7/14 5:31,3.59364,0.436908,0.179893,0.113087,0.014769,2014-10-07 05:31:00,10.200625,0.254193,NaN,NaN,0.002833,1.920083,1.866646
3488,10/7/14 5:39,3.28260,0.415025,0.171286,0.117386,0.014455,2014-10-07 05:39:00,6.592083,0.251781,NaN,NaN,0.005833,2.603417,2.488187
3489,10/7/14 5:47,3.49687,0.413879,0.165382,0.102418,0.015130,2014-10-07 05:47:00,5.712735,0.250623,NaN,NaN,-0.011500,2.676917,2.524917
3490,10/7/14 5:55,3.46249,0.410492,0.157401,0.099520,0.017553,2014-10-07 05:55:00,3.538542,0.251262,NaN,NaN,0.683083,2.594667,3.326354
3491,10/7/14 6:03,3.64449,0.456510,0.176882,0.121874,0.014880,2014-10-07 06:03:00,4.097500,0.251758,NaN,NaN,0.309333,3.120857,3.183536
3492,10/7/14 6:11,3.56978,0.400528,0.162680,0.089315,0.013559,2014-10-07 06:11:00,7.181799,0.255634,NaN,NaN,NaN,NaN,NaN
3493,10/7/14 6:19,3.54206,0.426877,0.182481,0.134379,0.014367,2014-10-07 06:19:00,6.524426,0.259452,NaN,NaN,NaN,NaN,NaN
3494,10/7/14 6:27,3.74740,0.439683,0.178564,0.118838,0.019787,2014-10-07 06:27:00,3.706667,0.260420,NaN,NaN,NaN,NaN,NaN
3495,10/7/14 6:35,3.54165,0.404511,0.156500,0.074379,0.012201,2014-10-07 06:35:00,2.888494,0.263080,NaN,NaN,NaN,NaN,NaN
3496,10/7/14 6:43,3.92832,0.431506,0.169920,0.090939,0.009973,2014-10-07 06:43:00,3.860208,0.269827,NaN,NaN,NaN,NaN,NaN
3497,10/7/14 6:51,3.71074,0.406377,0.163834,0.097348,0.010016,2014-10-07 06:51:00,3.268333,0.276950,NaN,NaN,NaN,NaN,NaN
3498,10/7/14 6:59,3.83711,0.436011,0.185121,0.133221,0.016204,2014-10-07 06:59:00,3.878452,0.275092,NaN,NaN,NaN,NaN,NaN
3499,10/7/14 7:07,3.49699,0.416138,0.170805,0.121061,0.019421,2014-10-07 07:07:00,2.124843,0.272896,NaN,NaN,1.014667,2.901000,NaN
3500,10/7/14 7:15,3.62281,0.437124,0.182971,0.149564,0.018648,2014-10-07 07:15:00,2.884167,0.271321,NaN,NaN,0.032417,3.230083,NaN
3501,10/7/14 7:23,3.47759,0.388631,0.156868,0.086987,0.011849,2014-10-07 07:23:00,2.160625,0.269548,NaN,NaN,0.854750,3.338250,NaN
3502,10/7/14 7:31,3.40688,0.360445,0.149370,0.074296,0.012681,2014-10-07 07:31:00,2.214614,0.270346,NaN,NaN,0.153583,3.374000,NaN
3503,10/7/14 7:39,3.49734,0.405758,0.176307,0.116643,0.015785,2014-10-07 07:39:00,2.317708,0.268689,NaN,NaN,1.057667,3.211750,NaN
3504,10/7/14 7:47,3.32166,0.390846,0.155536,0.092146,0.013268,2014-10-07 07:47:00,0.886458,0.268921,NaN,NaN,3.134167,2.345000,NaN
3505,10/7/14 7:55,3.48861,0.409975,0.166215,0.115080,0.015916,2014-10-07 07:55:00,1.077083,0.270000,NaN,NaN,0.657167,3.264583,NaN
3506,10/7/14 8:03,3.61874,0.395088,0.157430,0.115528,0.012686,2014-10-07 08:03:00,0.726096,0.272174,NaN,NaN,3.502583,2.459917,NaN
3507,10/7/14 8:11,3.54606,0.387418,0.149236,0.085049,0.010997,2014-10-07 08:11:00,0.659167,0.273319,NaN,NaN,2.455583,2.677167,4.175158
3508,10/7/14 8:19,3.45760,0.423594,0.156946,0.085992,0.007713,2014-10-07 08:19:00,0.845720,0.274787,NaN,NaN,1.824417,2.496917,4.153479
3509,10/7/14 8:27,3.46601,0.381894,0.138915,0.070869,0.008102,2014-10-07 08:27:00,0.715449,0.274747,NaN,NaN,1.212333,2.773333,3.760437
3510,10/7/14 8:35,3.48122,0.414889,0.158388,0.069350,0.008544,2014-10-07 08:35:00,1.118958,0.272492,NaN,NaN,0.822750,2.806250,3.349333
3511,10/7/14 8:43,3.42163,0.383357,0.152665,0.084453,0.010747,2014-10-07 08:43:00,0.873958,0.273140,NaN,NaN,0.732917,2.386917,3.085583
3512,10/7/14 8:51,3.54255,0.404184,0.155790,0.091699,0.011873,2014-10-07 08:51:00,1.552083,0.272416,NaN,NaN,0.397083,2.285917,2.622875
3513,10/7/14 8:59,3.54403,0.414546,0.158603,0.093408,0.009941,2014-10-07 08:59:00,1.745511,0.272832,NaN,NaN,0.454417,2.227750,2.524521
3514,10/7/14 9:07,3.67001,0.408091,0.165828,0.108439,0.012156,2014-10-07 09:07:00,2.468267,0.271029,NaN,NaN,0.808333,2.414167,3.063438

In [14]:
dfSO2 = read_2tracegas('SO2_cali', 'SO2', 'Trace_Gases-T3/9-2014_SO2.txt', 'Trace_Gases-T3/10-2014_SO2.txt', 1)
dfSO2

               datentime  SO2_cali       SO2
0    2014-09-13 17:47:00  0.223290  0.207045
1    2014-09-13 17:55:00  0.033663  0.041872
2    2014-09-13 18:03:00 -0.006153 -0.010868
3    2014-09-13 18:11:00 -0.066674 -0.070733
4    2014-09-13 18:19:00 -0.173570 -0.158297
5    2014-09-13 18:27:00 -0.070864 -0.090302
6    2014-09-13 18:35:00 -0.187757 -0.178384
7    2014-09-13 18:43:00 -0.222284 -0.228696
8    2014-09-13 18:51:00 -0.333882 -0.331604
9    2014-09-13 18:59:00 -0.338668 -0.336337
10   2014-09-13 19:07:00 -0.194476 -0.190477
11   2014-09-13 19:15:00 -0.256468 -0.266623
12   2014-09-13 19:23:00 -0.258591 -0.250128
13   2014-09-13 19:31:00 -0.273246 -0.277441
14   2014-09-13 19:39:00 -0.254235 -0.254713
15   2014-09-13 19:47:00 -0.216523 -0.210897
16   2014-09-13 19:55:00 -0.263214 -0.259809
17   2014-09-13 20:03:00 -0.178886 -0.190312
18   2014-09-13 20:11:00 -0.386105 -0.379068
19   2014-09-13 20:19:00 -0.388037 -0.385079
20   2014-09-13 20:27:00 -0.241575 -0.246698
21   2014-09-13 20:35:00 -0.262072 -0.265677
22   2014-09-13 20:43:00 -0.248029 -0.245435
23   2014-09-13 20:51:00 -0.326407 -0.327156
24   2014-09-13 20:59:00 -0.266485 -0.269205
25   2014-09-13 21:07:00 -0.288164 -0.281952
26   2014-09-13 21:15:00 -0.160484 -0.164190
27   2014-09-13 21:23:00 -0.199043 -0.196572
28   2014-09-13 21:31:00 -0.351739 -0.350269
29   2014-09-13 21:39:00 -0.202973 -0.206789
...                  ...       ...       ...
4226 2014-10-07 05:15:00 -0.296122 -0.289742
4227 2014-10-07 05:23:00 -0.246263 -0.251311
4228 2014-10-07 05:31:00 -0.221397 -0.212321
4229 2014-10-07 05:39:00 -0.203988 -0.207489
4230 2014-10-07 05:47:00 -0.106631 -0.114740
4231 2014-10-07 05:55:00 -0.129637 -0.119570
4232 2014-10-07 06:03:00 -0.225425 -0.222829
4233 2014-10-07 06:11:00 -0.166633 -0.170700
4234 2014-10-07 06:19:00 -0.133326 -0.140753
4235 2014-10-07 06:27:00 -0.269631 -0.267509
4236 2014-10-07 06:35:00 -0.285546 -0.279269
4237 2014-10-07 06:43:00 -0.111199 -0.111678
4238 2014-10-07 06:51:00 -0.093837 -0.104700
4239 2014-10-07 06:59:00 -0.219457 -0.215595
4240 2014-10-07 07:07:00 -0.129625 -0.131871
4241 2014-10-07 07:15:00 -0.268213 -0.262634
4242 2014-10-07 07:23:00 -0.164925 -0.170415
4243 2014-10-07 07:31:00 -0.090554 -0.092371
4244 2014-10-07 07:39:00 -0.226326 -0.216754
4245 2014-10-07 07:47:00 -0.233456 -0.232081
4246 2014-10-07 07:55:00 -0.221315 -0.226071
4247 2014-10-07 08:03:00 -0.190115 -0.192797
4248 2014-10-07 08:11:00 -0.178741 -0.172630
4249 2014-10-07 08:19:00 -0.251183 -0.251937
4250 2014-10-07 08:27:00 -0.102463 -0.105679
4251 2014-10-07 08:35:00 -0.059285 -0.060385
4252 2014-10-07 08:43:00 -0.082308 -0.076815
4253 2014-10-07 08:51:00 -0.164974 -0.171153
4254 2014-10-07 08:59:00 -0.386279 -0.377796
4255 2014-10-07 09:07:00 -0.191103 -0.192783

[4256 rows x 3 columns]

In [15]:
newdf = pd.merge(newdf, dfSO2, how='left', on=['datentime'])
newdf

,Time stop,Organic,Sulfate,Ammonium,Nitrate,Chloride,datentime,Ozone,CO,N2O,H2O,NO,NO2,NOy,SO2_cali,SO2
0,9/13/14 17:47,11.94720,1.758410,0.550953,0.290176,0.015616,2014-09-13 17:47:00,66.524375,0.178201,0.307698,30919.728814,-0.028833,1.063667,3.284333,0.223290,0.207045
1,9/13/14 17:55,11.20270,1.590140,0.515114,0.211021,0.013689,2014-09-13 17:55:00,61.587474,0.174315,0.307689,31046.698312,-0.042333,0.995333,3.094375,0.033663,0.041872
2,9/13/14 18:03,10.73810,1.484200,0.456858,0.174378,0.014700,2014-09-13 18:03:00,49.494781,0.157262,0.307984,29523.415254,-0.032667,0.735583,2.211396,-0.006153,-0.010868
3,9/13/14 18:11,11.26250,1.562690,0.477693,0.174844,0.017399,2014-09-13 18:11:00,50.088125,0.157871,0.307962,29601.052854,-0.036000,0.749917,2.296271,-0.066674,-0.070733
4,9/13/14 18:19,11.69100,1.582690,0.503957,0.194480,0.016549,2014-09-13 18:19:00,50.118580,0.163030,0.307179,31677.964059,-0.023917,0.832750,2.538750,-0.173570,-0.158297
5,9/13/14 18:27,11.38780,1.580270,0.510905,0.164823,0.018170,2014-09-13 18:27:00,45.937292,0.161223,0.306634,32611.820296,-0.016250,0.843917,2.262146,-0.070864,-0.090302
6,9/13/14 18:35,10.95210,1.450210,0.453779,0.162619,0.008872,2014-09-13 18:35:00,37.641458,0.150850,0.306826,31608.273305,-0.008750,0.665500,1.659854,-0.187757,-0.178384
7,9/13/14 18:43,10.92600,1.433650,0.476453,0.152684,0.016209,2014-09-13 18:43:00,34.505010,0.150003,0.306567,32419.156780,0.000917,0.743917,1.641729,-0.222284,-0.228696
8,9/13/14 18:51,3.88525,0.595637,0.171677,0.038497,0.009524,2014-09-13 18:51:00,38.534167,0.133811,0.307636,28294.280591,-0.000333,0.456000,1.183208,-0.333882,-0.331604
9,9/13/14 18:59,3.55995,0.596208,0.174129,0.047259,0.009437,2014-09-13 18:59:00,45.923125,0.125564,0.308413,24998.076271,-0.079750,0.537167,1.054812,-0.338668,-0.336337
10,9/13/14 19:07,5.94130,0.900445,0.284233,0.046628,0.010277,2014-09-13 19:07:00,44.671339,0.127440,0.308005,25315.139831,-0.071250,0.522083,1.047417,-0.194476,-0.190477
11,9/13/14 19:15,5.81877,0.900757,0.275290,0.082913,0.009717,2014-09-13 19:15:00,40.412500,0.132527,0.306779,27501.997886,-0.036167,0.540833,1.058500,-0.256468,-0.266623
12,9/13/14 19:23,4.63620,0.753188,0.230268,0.043465,0.008388,2014-09-13 19:23:00,37.465971,0.129414,0.306801,27917.350951,-0.048417,0.716250,1.243521,-0.258591,-0.250128
13,9/13/14 19:31,4.92573,0.777560,0.259077,0.071588,0.011794,2014-09-13 19:31:00,36.526514,0.130256,0.306816,28031.723992,0.013417,0.812750,1.307521,-0.273246,-0.277441
14,9/13/14 19:39,4.74542,0.735238,0.239229,0.055658,0.008778,2014-09-13 19:39:00,33.351042,0.130023,0.306406,29104.974630,-0.048583,1.033250,1.521208,-0.254235,-0.254713
15,9/13/14 19:47,4.55860,0.729764,0.224972,0.049968,0.002318,2014-09-13 19:47:00,30.068958,0.135835,0.306392,29037.695560,0.012583,1.094500,1.588146,-0.216523,-0.210897
16,9/13/14 19:55,4.46460,0.742671,0.236612,0.039686,0.012152,2014-09-13 19:55:00,29.719874,0.129636,0.306504,28853.359408,-0.021500,1.026417,1.484417,-0.263214,-0.259809
17,9/13/14 20:03,4.72083,0.719964,0.224486,0.060566,0.011382,2014-09-13 20:03:00,24.106263,0.131238,0.306206,29710.691332,-0.002000,0.816833,1.228563,-0.178886,-0.190312
18,9/13/14 20:18,4.47290,0.708016,0.231971,0.062088,0.009520,2014-09-13 20:18:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,9/13/14 20:27,4.81421,0.722954,0.226816,0.045545,0.004908,2014-09-13 20:27:00,17.889583,0.134608,0.306041,30764.598726,0.533500,0.237667,2.050938,-0.241575,-0.246698
20,9/13/14 20:35,4.58972,0.715477,0.220541,0.054783,0.009497,2014-09-13 20:35:00,16.370000,0.135521,0.305811,30975.292373,0.025083,0.863083,1.205896,-0.262072,-0.265677
21,9/13/14 20:43,4.63345,0.717325,0.208483,0.064670,0.009046,2014-09-13 20:43:00,14.955230,0.136636,0.305816,31040.696203,0.042083,0.735333,1.129646,-0.248029,-0.245435
22,9/13/14 20:51,4.59768,0.697670,0.215358,0.046874,0.012505,2014-09-13 20:51:00,12.166667,0.136587,0.305498,31582.762208,0.017917,0.879667,1.212104,-0.326407,-0.327156
23,9/13/14 20:59,4.45570,0.694825,0.202789,0.052401,0.010564,2014-09-13 20:59:00,12.136667,0.138346,0.305749,31431.852008,0.039583,1.009667,1.327479,-0.266485,-0.269205
24,9/13/14 21:07,4.89321,0.709334,0.216529,0.058691,0.012774,2014-09-13 21:07:00,11.982636,0.136948,0.305989,31692.137712,0.026667,0.956167,1.335771,-0.288164,-0.281952
25,9/13/14 21:15,6.70487,0.976280,0.344037,0.099350,0.013693,2014-09-13 21:15:00,15.215833,0.141294,0.306334,31566.287526,0.014417,0.838167,1.182333,-0.160484,-0.164190
26,9/13/14 21:39,7.37721,1.113250,0.386505,0.087294,0.016271,2014-09-13 21:39:00,22.937996,0.148556,0.306925,30526.359408,-0.046583,1.042750,1.366854,-0.202973,-0.206789
27,9/13/14 21:47,7.27039,1.082220,0.366399,0.079883,0.010590,2014-09-13 21:47:00,23.530417,0.144452,0.306950,30330.042373,-0.035333,0.900750,1.304292,-0.298810,-0.295261
28,9/13/14 21:55,7.39930,1.121050,0.381587,0.086474,0.012381,2014-09-13 21:55:00,26.245188,0.143281,0.307129,29860.452431,-0.029500,0.955833,1.384292,-0.203406,-0.209344
29,9/13/14 22:03,7.51275,1.128130,0.382217,0.081971,0.016134,2014-09-13 22:03:00,28.223690,0.142224,0.307397,29550.672304,-0.042667,0.861833,1.369083,-0.265679,-0.259536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3485,10/7/14 5:15,3.86336,0.468469,0.170375,0.092328,0.012988,2014-10-07 05:15:00,6.170833,0.261465,NaN,NaN,0.049667,2.976083,2.880062,-0.296122,-0.289742
3486,10/7/14 5:23,3.65903,0.440940,0.171434,0.105964,0.015694,2014-10-07 05:23:00,8.608577,0.257929,NaN,NaN,0.025250,2.319750,2.271542,-0.246263,-0.251311
3487,10/7/14 5:31,3.59364,0.436908,0.179893,0.113087,0.014769,2014-10-07 05:31:00,10.200625,0.254193,NaN,NaN,0.002833,1.920083,1.866646,-0.221397,-0.212321
3488,10/7/14 5:39,3.28260,0.415025,0.171286,0.117386,0.014455,2014-10-07 05:39:00,6.592083,0.251781,NaN,NaN,0.005833,2.603417,2.488187,-0.203988,-0.207489
3489,10/7/14 5:47,3.49687,0.413879,0.165382,0.102418,0.015130,2014-10-07 05:47:00,5.712735,0.250623,NaN,NaN,-0.011500,2.676917,2.524917,-0.106631,-0.114740
3490,10/7/14 5:55,3.46249,0.410492,0.157401,0.099520,0.017553,2014-10-07 05:55:00,3.538542,0.251262,NaN,NaN,0.683083,2.594667,3.326354,-0.129637,-0.119570
3491,10/7/14 6:03,3.64449,0.456510,0.176882,0.121874,0.014880,2014-10-07 06:03:00,4.097500,0.251758,NaN,NaN,0.309333,3.120857,3.183536,-0.225425,-0.222829
3492,10/7/14 6:11,3.56978,0.400528,0.162680,0.089315,0.013559,2014-10-07 06:11:00,7.181799,0.255634,NaN,NaN,NaN,NaN,NaN,-0.166633,-0.170700
3493,10/7/14 6:19,3.54206,0.426877,0.182481,0.134379,0.014367,2014-10-07 06:19:00,6.524426,0.259452,NaN,NaN,NaN,NaN,NaN,-0.133326,-0.140753
3494,10/7/14 6:27,3.74740,0.439683,0.178564,0.118838,0.019787,2014-10-07 06:27:00,3.706667,0.260420,NaN,NaN,NaN,NaN,NaN,-0.269631,-0.267509
3495,10/7/14 6:35,3.54165,0.404511,0.156500,0.074379,0.012201,2014-10-07 06:35:00,2.888494,0.263080,NaN,NaN,NaN,NaN,NaN,-0.285546,-0.279269
3496,10/7/14 6:43,3.92832,0.431506,0.169920,0.090939,0.009973,2014-10-07 06:43:00,3.860208,0.269827,NaN,NaN,NaN,NaN,NaN,-0.111199,-0.111678
3497,10/7/14 6:51,3.71074,0.406377,0.163834,0.097348,0.010016,2014-10-07 06:51:00,3.268333,0.276950,NaN,NaN,NaN,NaN,NaN,-0.093837,-0.104700
3498,10/7/14 6:59,3.83711,0.436011,0.185121,0.133221,0.016204,2014-10-07 06:59:00,3.878452,0.275092,NaN,NaN,NaN,NaN,NaN,-0.219457,-0.215595
3499,10/7/14 7:07,3.49699,0.416138,0.170805,0.121061,0.019421,2014-10-07 07:07:00,2.124843,0.272896,NaN,NaN,1.014667,2.901000,NaN,-0.129625,-0.131871
3500,10/7/14 7:15,3.62281,0.437124,0.182971,0.149564,0.018648,2014-10-07 07:15:00,2.884167,0.271321,NaN,NaN,0.032417,3.230083,NaN,-0.268213,-0.262634
3501,10/7/14 7:23,3.47759,0.388631,0.156868,0.086987,0.011849,2014-10-07 07:23:00,2.160625,0.269548,NaN,NaN,0.854750,3.338250,NaN,-0.164925,-0.170415
3502,10/7/14 7:31,3.40688,0.360445,0.149370,0.074296,0.012681,2014-10-07 07:31:00,2.214614,0.270346,NaN,NaN,0.153583,3.374000,NaN,-0.090554,-0.092371
3503,10/7/14 7:39,3.49734,0.405758,0.176307,0.116643,0.015785,2014-10-07 07:39:00,2.317708,0.268689,NaN,NaN,1.057667,3.211750,NaN,-0.226326,-0.216754
3504,10/7/14 7:47,3.32166,0.390846,0.155536,0.092146,0.013268,2014-10-07 07:47:00,0.886458,0.268921,NaN,NaN,3.134167,2.345000,NaN,-0.233456,-0.232081
3505,10/7/14 7:55,3.48861,0.409975,0.166215,0.115080,0.015916,2014-10-07 07:55:00,1.077083,0.270000,NaN,NaN,0.657167,3.264583,NaN,-0.221315,-0.226071
3506,10/7/14 8:03,3.61874,0.395088,0.157430,0.115528,0.012686,2014-10-07 08:03:00,0.726096,0.272174,NaN,NaN,3.502583,2.459917,NaN,-0.190115,-0.192797
3507,10/7/14 8:11,3.54606,0.387418,0.149236,0.085049,0.010997,2014-10-07 08:11:00,0.659167,0.273319,NaN,NaN,2.455583,2.677167,4.175158,-0.178741,-0.172630
3508,10/7/14 8:19,3.45760,0.423594,0.156946,0.085992,0.007713,2014-10-07 08:19:00,0.845720,0.274787,NaN,NaN,1.824417,2.496917,4.153479,-0.251183,-0.251937
3509,10/7/14 8:27,3.46601,0.381894,0.138915,0.070869,0.008102,2014-10-07 08:27:00,0.715449,0.274747,NaN,NaN,1.212333,2.773333,3.760437,-0.102463,-0.105679
3510,10/7/14 8:35,3.48122,0.414889,0.158388,0.069350,0.008544,2014-10-07 08:35:00,1.118958,0.272492,NaN,NaN,0.822750,2.806250,3.349333,-0.059285,-0.060385
3511,10/7/14 8:43,3.42163,0.383357,0.152665,0.084453,0.010747,2014-10-07 08:43:00,0.873958,0.273140,NaN,NaN,0.732917,2.386917,3.085583,-0.082308,-0.076815
3512,10/7/14 8:51,3.54255,0.404184,0.155790,0.091699,0.011873,2014-10-07 08:51:00,1.552083,0.272416,NaN,NaN,0.397083,2.285917,2.622875,-0.164974,-0.171153
3513,10/7/14 8:59,3.54403,0.414546,0.158603,0.093408,0.009941,2014-10-07 08:59:00,1.745511,0.272832,NaN,NaN,0.454417,2.227750,2.524521,-0.386279,-0.377796
3514,10/7/14 9:07,3.67001,0.408091,0.165828,0.108439,0.012156,2014-10-07 09:07:00,2.468267,0.271029,NaN,NaN,0.808333,2.414167,3.063438,-0.191103,-0.192783

In [17]:
Species = ['Organic', 'Sulfate', 'Ammonium', 'Nitrate', 'Chloride', 
           'Ozone', 'CO', 'N2O', 'H2O', 'NO', 'NO2', 'NOy', 'SO2']

def nix(val, lst):
    return [x for x in lst if x != val]

@lru_cache()
def load_ticker(ticker):
    return pd.DataFrame({ticker: newdf[ticker]})

@lru_cache()
def get_data(t1, t2):
    df1 = load_ticker(t1)
    df2 = load_ticker(t2)
    df3 = load_ticker('datentime')
    data = pd.concat([df1, df2, df3], axis=1)
    data = data.dropna()
    data['t1'] = data[t1]
    data['t2'] = data[t2]
    return data

# set up widgets
interval = PreText(text='', width=400)
stats = PreText(text='', width=400)
ticker1 = Select(value="Organic", options=nix('Sulfate', Species))
ticker2 = Select(value="Sulfate", options=nix('Organic', Species))

# set up plots

source = ColumnDataSource(data=dict(index=[], t1=[], t2=[], datentime=[]))
source_static = ColumnDataSource(data=dict(index=[], t1=[], t2=[], datentime=[]))
corrtoollist = 'pan, box_zoom, box_select, save, reset'
toollist = 'pan, box_zoom, xzoom_in, xzoom_out, yzoom_in, yzoom_out, xbox_select, save, reset'


hovertool = HoverTool(
    tooltips=[
#        ('Date and Time','@datentime{%F %T}'),
        ('Concentration','$y'),
            ],
#     formatters={
#         'Date and Time': 'datetime',
#     },
)


# corr = figure(plot_width=400, plot_height=400, tools=corrtoollist)
# corr.background_fill_color= '#efefef'
# corr.background_fill_alpha= 0.3 
# corr.circle('t1', 't2', size=2, source=source, alpha=0.4,
#             color='black', nonselection_color='black', 
#             selection_color='#e98043', 
#             nonselection_alpha=0.4, selection_alpha=0.8)
# corr.xaxis.axis_label_text_font_style = 'bold'
# corr.yaxis.axis_label_text_font_style = 'bold'

corr = figure(plot_width=400, plot_height=400, tools=corrtoollist)
corr.background_fill_color= '#efefef'
corr.background_fill_alpha= 0.3 
corr.circle('t1', 't2', size=2, source=source, alpha=0.4,
            color='black', nonselection_color='black', 
            selection_color='#e98043', 
            nonselection_alpha=0.4, selection_alpha=0.8)
corr.xaxis.axis_label_text_font_style = 'bold'
corr.yaxis.axis_label_text_font_style = 'bold'
corrhovertool = HoverTool(
    tooltips=[
#        ('Date and Time','@datentime{%F}'),
        ('x','$x'),
        ('y','$y'),
            ],
#     formatters={
#         'Date and Time': 'datetime',
#     }
    )
corr.add_tools(corrhovertool)

ts1 = figure(plot_width=900, plot_height=200, tools=toollist, toolbar_location='above', 
             x_axis_type='datetime', active_drag='box_zoom', active_inspect=None)
ts1.background_fill_color= '#efefef'
ts1.background_fill_alpha = 0.3
ts1.circle('datentime', 't1', size=2, source=source_static,
           color='black', 
           alpha=0.4)
ts1.circle('datentime', 't1', size=2, source=source, alpha=0.4,
           color='black', nonselection_color='black', 
           selection_color='#e98043', 
           nonselection_alpha=0.4, selection_alpha=0.8)
ts1.add_tools(hovertool)
ts1.xaxis.axis_label = 'Date and Time'
ts1.xaxis.axis_label_text_color = 'black'
ts1.xaxis.axis_label_text_font_style = 'bold'
ts1.xaxis.axis_label_standoff = 10
ts1.yaxis.axis_label = 'Conc. [ppbv]'
ts1.yaxis.axis_label_text_color = 'black'
ts1.yaxis.axis_label_text_font_style = 'bold'
ts1.yaxis.axis_label_standoff = 10
ts1.xaxis.formatter = DatetimeTickFormatter(
        minutes='%m/%d %H:%M',
        hours='%m/%d %H:%M',
        days='%m/%d %H:%M',
        months='%m/%d %H:%M',
    )

ts2 = figure(plot_width=900, plot_height=200, tools=toollist, toolbar_location='above', 
             x_axis_type='datetime', active_drag='box_zoom', active_inspect=None)
ts2.x_range = ts1.x_range
ts2.background_fill_color= '#efefef'
ts2.background_fill_alpha = 0.3
ts2.circle('datentime', 't2', size=2, source=source_static, 
           color='black', 
           alpha=0.4)
ts2.circle('datentime', 't2', size=2, source=source, alpha=0.4,
           color='black', nonselection_color='black', 
           selection_color='#e98043', 
           nonselection_alpha=0.4, selection_alpha=0.8)
ts2.add_tools(hovertool)
ts2.xaxis.axis_label = 'Date and Time'
ts2.xaxis.axis_label_text_color = 'black'
ts2.xaxis.axis_label_text_font_style = 'bold'
ts2.xaxis.axis_label_standoff = 10
ts2.yaxis.axis_label = 'Conc. [ppbv]'
ts2.yaxis.axis_label_text_color = 'black'
ts2.yaxis.axis_label_text_font_style = 'bold'
ts2.yaxis.axis_label_standoff = 10
ts2.xaxis.formatter = DatetimeTickFormatter(
        minutes='%m/%d %H:%M',
        hours='%m/%d %H:%M',
        days='%m/%d %H:%M',
        months='%m/%d %H:%M',
    )

# set up callbacks

def ticker1_change(attrname, old, new):
    ticker2.options = nix(new, Species)
    update()
    
def ticker2_change(attrname, old, new):
    ticker1.options = nix(new, Species)
    update()
    
def update(selected=None):
    t1, t2 = ticker1.value, ticker2.value
    
    dfile = get_data(t1, t2)
    data = dfile[['t1', 't2', 'datentime']]
    source.data = data
    source_static.data = data
    
    update_interval(dfile)
    update_stats(dfile, t1, t2)
    
    corr.title.text = '%s vs %s' % (t2, t1)
    corr.xaxis.axis_label = '%s' % t1
    corr.yaxis.axis_label = '%s' % t2
    
    ts1.title.text, ts2.title.text = '%s species over time in 2014' % t1, '%s species over time in 2014' % t2


def update_interval(data):
    interval.text = 'From %s To %s' % (data['datentime'].iloc[0], data['datentime'].iloc[-1])
    
def update_stats(data, t1, t2):
    stats.text = str(data[[t1, t2]].describe())
    
ticker1.on_change('value', ticker1_change)
ticker2.on_change('value', ticker2_change)

def selection_change(attrname, old, new):
    t1, t2 = ticker1.value, ticker2.value
    data = get_data(t1, t2)
    selected = source.selected.indices
    if selected:
        data = data.iloc[selected, :]
    update_interval(data)
    update_stats(data, t1, t2)
    
source.selected.on_change('indices', selection_change)

# set up layout

widgets = column(ticker1, ticker2, interval, stats)
main_row = row(widgets, corr)
series = column(ts1, ts2)
layout = column(main_row, series)

# initialize

update()

curdoc().add_root(layout)
curdoc().title = 'project_Bokeh'
show(layout)

/anaconda3/lib/python3.6/site-packages/bokeh/plotting/helpers.py:628: UserWarning: ZoomInTool,ZoomOutTool are being repeated
  warnings.warn("%s are being repeated" % ",".join(repeated_tools))
WARNING:bokeh.embed.util:
You are generating standalone HTML/JS output, but trying to use real Python
callbacks (i.e. with on_change or on_event). This combination cannot work.

Only JavaScript callbacks may be used with standalone output. For more
information on JavaScript callbacks with Bokeh, see:

    http://bokeh.pydata.org/en/latest/docs/user_guide/interaction/callbacks.html

Alternatively, to use real Python callbacks, a Bokeh server application may
be used. For more information on building and running Bokeh applications, see:

    http://bokeh.pydata.org/en/latest/docs/user_guide/server.html

In [ ]:
# output_notebook()
# output_file("AMS data correlation.html", title='project')

In [16]:
# To do's:
# units for time series
# histogram
# add my own data